#!/usr/bin/env python3
"""Scaffold a Codeforces-style problem workspace from local templates."""

from __future__ import annotations

import argparse
import re
from pathlib import Path

SKILL_ROOT = Path(__file__).resolve().parents[1]
TEMPLATE_DIR = SKILL_ROOT / "assets" / "templates"
REPO_ROOT = Path(__file__).resolve().parents[4]
DEFAULT_OUTPUT_ROOT = REPO_ROOT / "tools" / "level"
DEFAULT_LEVELS_DIR = REPO_ROOT / "assets" / "levels"


def write_file(path: Path, content: str, force: bool) -> None:
    if path.exists() and not force:
        raise FileExistsError(f"Refusing to overwrite existing file: {path}")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def load_template(name: str) -> str:
    template_path = TEMPLATE_DIR / name
    return template_path.read_text(encoding="utf-8")


def validate_identifier(value: str, *, field_name: str) -> str:
    cleaned = value.strip()
    if not cleaned:
        raise ValueError(f"{field_name} must not be empty")
    if not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9_-]*", cleaned):
        raise ValueError(
            f"{field_name} must match [A-Za-z0-9][A-Za-z0-9_-]* (got: {value!r})"
        )
    return cleaned


def ensure_levels_index(index_path: Path) -> None:
    if index_path.exists():
        return
    index_path.parent.mkdir(parents=True, exist_ok=True)
    index_path.write_text("levels:\n", encoding="utf-8")


def register_level_in_index(index_path: Path, *, level_id: str, level_file: str) -> bool:
    text = index_path.read_text(encoding="utf-8")
    if f"id: {level_id}" in text:
        return False
    if not text.endswith("\n"):
        text += "\n"
    text += f"  - id: {level_id}\n"
    text += f"    file: {level_file}\n"
    index_path.write_text(text, encoding="utf-8")
    return True


def level_yaml_template(*, level_id: str, title: str, testcase_dir: str, time_limit_ms: int, memory_limit_mb: int) -> str:
    return f"""level_id: {level_id}
title: {title}
chapter_id: custom
order_index: 1
prompt: |
  Read an integer n, then read n integers.
  Output the sum of the n integers.
learning_markdown: |
  This scaffold is generated by cf-testlib-problem-generation.
  Replace prompt/testcases/judge settings with your actual problem.
testcase_dir: {testcase_dir}
judge_policy:
  time_limit_ms: {time_limit_ms}
  memory_limit_mb: {memory_limit_mb}
metadata:
  stage: generated
  source: cf-testlib-problem-generation
"""


def problem_readme_template(*, problem_name: str, level_id: str) -> str:
    return f"""# {problem_name}

This workspace is generated for CF-style authoring and Block2Python integration.

## Paths

- Scripts and references: tools/level/{problem_name}
- Level definition: assets/levels/{level_id}.yaml
- Level cases: assets/levels/cases/{level_id}

## Next Steps

1. Update statement.md with the final problem statement.
2. Implement testlib files under testlib/.
3. Generate `.in/.out` files into assets/levels/cases/{level_id}/.
4. Replace placeholder sample cases and tune judge_policy in assets/levels/{level_id}.yaml.
"""


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Create a CF/testlib scaffold aligned with Block2Python levels/judge format.",
    )
    parser.add_argument("problem_name", help="Folder name under tools/level/")
    parser.add_argument(
        "--level-id",
        help="Level id used by assets/levels/<level-id>.yaml (default: problem_name)",
    )
    parser.add_argument(
        "--title",
        help="Human-readable level title (default: level id)",
    )
    parser.add_argument(
        "--output-root",
        default=str(DEFAULT_OUTPUT_ROOT),
        help="Root directory for generated problem scripts (default: repo/tools/level)",
    )
    parser.add_argument(
        "--levels-dir",
        default=str(DEFAULT_LEVELS_DIR),
        help="Levels root directory containing index.yaml (default: repo/assets/levels)",
    )
    parser.add_argument(
        "--time-limit-ms",
        type=int,
        default=2000,
        help="judge_policy.time_limit_ms for generated level yaml",
    )
    parser.add_argument(
        "--memory-limit-mb",
        type=int,
        default=256,
        help="judge_policy.memory_limit_mb for generated level yaml",
    )
    parser.add_argument(
        "--register-index",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Append generated level to assets/levels/index.yaml (default: enabled)",
    )
    parser.add_argument(
        "--skip-level-assets",
        action="store_true",
        help="Only scaffold tools/level workspace, do not create assets/levels files",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite existing files if present",
    )
    args = parser.parse_args()

    problem_name = validate_identifier(args.problem_name, field_name="problem_name")
    level_id = validate_identifier(args.level_id or problem_name, field_name="level_id")
    title = (args.title or level_id).strip()
    if not title:
        raise ValueError("title must not be empty")

    if args.time_limit_ms <= 0:
        raise ValueError("--time-limit-ms must be > 0")
    if args.memory_limit_mb <= 0:
        raise ValueError("--memory-limit-mb must be > 0")

    output_root = Path(args.output_root).resolve()
    problem_root = output_root / problem_name

    (problem_root / "solutions").mkdir(parents=True, exist_ok=True)
    (problem_root / "testlib").mkdir(parents=True, exist_ok=True)
    (problem_root / "tests" / "samples").mkdir(parents=True, exist_ok=True)
    (problem_root / "tests" / "pretests").mkdir(parents=True, exist_ok=True)
    (problem_root / "tests" / "system").mkdir(parents=True, exist_ok=True)

    statement = """# Problem Title

## Statement

[TODO]

## Input

[TODO]

## Output

[TODO]

## Constraints

- [TODO]

## Notes

- [TODO]
"""

    write_file(problem_root / "statement.md", statement, args.force)
    write_file(problem_root / "README.md", problem_readme_template(problem_name=problem_name, level_id=level_id), args.force)

    write_file(
        problem_root / "solutions" / "solution.cpp",
        load_template("solution.cpp"),
        args.force,
    )
    write_file(
        problem_root / "solutions" / "brute.cpp",
        load_template("brute.cpp"),
        args.force,
    )
    write_file(
        problem_root / "testlib" / "generator.cpp",
        load_template("generator.cpp"),
        args.force,
    )
    write_file(
        problem_root / "testlib" / "validator.cpp",
        load_template("validator.cpp"),
        args.force,
    )
    write_file(
        problem_root / "testlib" / "checker.cpp",
        load_template("checker.cpp"),
        args.force,
    )

    if not args.skip_level_assets:
        levels_dir = Path(args.levels_dir).resolve()
        index_path = levels_dir / "index.yaml"
        ensure_levels_index(index_path)

        level_file_name = f"{level_id}.yaml"
        testcase_dir_rel = f"cases/{level_id}"
        level_yaml_path = levels_dir / level_file_name
        cases_dir = levels_dir / "cases" / level_id
        cases_dir.mkdir(parents=True, exist_ok=True)

        write_file(
            level_yaml_path,
            level_yaml_template(
                level_id=level_id,
                title=title,
                testcase_dir=testcase_dir_rel,
                time_limit_ms=args.time_limit_ms,
                memory_limit_mb=args.memory_limit_mb,
            ),
            args.force,
        )
        write_file(cases_dir / "01.in", "3\n1 2 3\n", args.force)
        write_file(cases_dir / "01.out", "6\n", args.force)

        registered = False
        if args.register_index:
            registered = register_level_in_index(index_path, level_id=level_id, level_file=level_file_name)

        print(f"Scaffold created at: {problem_root}")
        print(f"Level yaml created at: {level_yaml_path}")
        print(f"Cases directory created at: {cases_dir}")
        if args.register_index:
            if registered:
                print(f"Registered in index: {index_path}")
            else:
                print(f"Level id already exists in index, skipped register: {index_path}")
    else:
        print(f"Scaffold created at: {problem_root}")

    print("Next: fill statement.md and adjust templates to your actual problem.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
